### ISSUE TITLE
Label/Listcell cannot be cast to org.zkoss.zul.Comboitem

### ISSUE THREAD

**Issue by szymonk92** [zkoss/zk#2688] opened 2021-10-27 15:35 UTC
When using combobox, I am sometimes getting 
`java.lang.ClassCastException: org.zkoss.zul.Listcell cannot be cast to org.zkoss.zul.Comboitem`
and 
`java.lang.ClassCastException: org.zkoss.zul.Label cannot be cast to org.zkoss.zul.Comboitem`
![ZKerror](https://user-images.githubusercontent.com/4785319/139098245-86958cb1-0c46-4388-89a9-200737e952d3.png)

How am I able to reproduce it in ma application? By clicking on comobox several times, and clicking around (I know, rough description!) 

It seems, that problem is in casting component to **Comboitem** without checking it's type.

```
   Comboitem prevSeld = (Comboitem) request.getDesktop()
         .getComponentByUuidIfAny((String) request.getData().get("prevSeld"));
```

and it seems I am not the only facing [this issue](https://tracker.zkoss.org/browse/ZK-4847) and [that](https://tracker.zkoss.org/browse/ZK-4509?page=com.atlassian.streams.streams-jira-plugin%3Aactivity-stream-issue-tab)

**Comment by jumperchen** [comment] 2021-11-08 02:46
The issue is fixed in [ZK-4509](https://tracker.zkoss.org/browse/ZK-4509?page=com.atlassian.streams.streams-jira-plugin%3Aactivity-stream-issue-tab) since 9.6.1.

**Closed by jumperchen** 2021-11-08 02:46 UTC
